# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'NATURAL'), (2, 'JURIDICO')], default=1)),
                ('nombre', models.CharField(max_length=255, verbose_name='razon social')),
                ('identificacion', models.CharField(max_length=14, verbose_name='RUC/CEDULA')),
                ('telefono', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, max_length=400, null=True)),
                ('sector', models.IntegerField(choices=[(1, 'AGROPECUARIO'), (2, 'AGUA'), (3, 'COMERCIO'), (4, 'CONSTRUCCION'), (5, 'DEFENSA'), (6, 'ENERGIA'), (7, 'GOBIERNO'), (8, 'INDUSTRIA'), (9, 'INGENIOS'), (10, 'PESCA'), (11, 'MINERIA'), (12, 'TRANSPORTE'), (13, 'OTROS'), (14, 'ESTACIONES DE SERVICIO')], default=1)),
                ('clasificacion', models.CharField(blank=True, max_length=3, null=True)),
                ('limite_credito', models.FloatField(default=0.0)),
                ('limite_descuento', models.FloatField(default=0.0)),
                ('plazo', models.PositiveIntegerField(default=0, help_text='plazo de credito en dias')),
                ('saldo', models.FloatField(default=0.0)),
                ('mora', models.FloatField(default=0.0, verbose_name='saldo en mora')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Departamento'),
        ),
    ]
