# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170613_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tc',
            options={'verbose_name': 'tasa de cambio', 'verbose_name_plural': 'tasas de cambio'},
        ),
        migrations.AlterField(
            model_name='tc',
            name='compra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tc',
            name='venta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
