# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170613_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='codigo',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_detallefactura_producto', to='base.Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
