# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170613_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='costo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='costo_promedio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='descuento',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='existencia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='saldo',
            field=models.FloatField(default=0.0),
        ),
    ]
